### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by xub** [grunch/MercadopagoBundle#1]
Hola, porque no es compatible con Symfony 3.0 ?? Saludos

**Comment by fjcalderon** [comment]
Puedes hacer el Pull Request de compatibilidad ;)

Saludos

**Comment by xub** [comment]
No tengo idea como hacer un Pull Request....  no se puede cambiar esta linea         "symfony/framework-bundle": "~2.6", ? para que sea compatible ?

**Comment by fjcalderon** [comment]
no he tenido tiempo de revisar que cambios trae el 3.0, pero es muy probable que funcione sin problema si le cambias precisamente el 2.6 por 3.0, prueba y me dices
